const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.jumpthru,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.RecreateInitialObjects,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Platform.Acts.SetVectorY
	];
};
self.C3_JsPropNameTable = [
	{Твёрдый: 0},
	{Пол: 0},
	{Потолок: 0},
	{Стена: 0},
	{Фон1: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Стив: 0},
	{СквознаяПлатформа: 0},
	{Платформа1: 0},
	{Платформа2: 0},
	{Клавиатура: 0},
	{Тач: 0},
	{Рестарт: 0},
	{Счетчик: 0},
	{Жизни: 0},
	{Угасание: 0},
	{Дым: 0},
	{ОбщийМонстр: 0},
	{Фон2: 0},
	{Валюта: 0},
	{правый: 0},
	{левый: 0},
	{о4ки: 0},
	{слур: 0},
	{хп: 0}
];

self.InstanceType = {
	Пол: class extends self.ISpriteInstance {},
	Потолок: class extends self.ISpriteInstance {},
	Стена: class extends self.ISpriteInstance {},
	Фон1: class extends self.ITiledBackgroundInstance {},
	Стив: class extends self.ISpriteInstance {},
	Платформа1: class extends self.ITiledBackgroundInstance {},
	Платформа2: class extends self.ITiledBackgroundInstance {},
	Клавиатура: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	Рестарт: class extends self.ISpriteInstance {},
	Счетчик: class extends self.ISpriteFontInstance {},
	Жизни: class extends self.ISpriteInstance {},
	Дым: class extends self.ISpriteInstance {},
	ОбщийМонстр: class extends self.ISpriteInstance {},
	Фон2: class extends self.ITiledBackgroundInstance {},
	Валюта: class extends self.ISpriteInstance {},
	правый: class extends self.ISpriteInstance {},
	левый: class extends self.ISpriteInstance {}
}